name: Simple CI Workflow

on:
  push:
    branches:
      - 'dev-pro'
      - 'dev-test'

jobs:
  deploy_to_dev_pro:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev-pro'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to dev-pro
      run: |
        echo "Deploying to dev-pro branch..."
        # Your deployment steps here

  deploy_to_dev_test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev-test'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to dev-test
      run: |
        echo "Deploying to dev-test branch..."
        # Your deployment steps here
